import type { Metadata } from "next";

import { Manrope, Poppins } from "next/font/google";
import "./globals.css";
import { NavigationBar } from "../components/navigations/navigation-bar";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Bright Digital",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${poppins.variable} max-w-[1520px] scroll-smooth antialiased overflow-x-hidden mx-auto`}>
        <NavigationBar />
        <main className="pt-[120px] md:pt-[150px]  w-screen  px-8 lg:px-12 min-h-screen overflow-x-hidden">
          {children}
        </main>
      </body>
    </html>
  );
}
